# core/editals_data.py
# Dados completos dos editais organizados por prioridade

EDITALS_DATA = {
    "Prioridade 1": [
        {
            "id": "p1_detran_mg_suspensao",
            "nome": "DETRAN MG — Suspensão",
            "estado": "MG",
            "tipo": "Suspensão",
            "edital_url": "https://detran.mg.gov.br/infracoes/suspensao-do-direito-de-dirigir/consulta-de-editais-do-processo-de-suspensao",
            "consulta_url": "https://detran.mg.gov.br/infracoes/suspensao-do-direito-de-dirigir/consulta-de-processo-de-suspensao",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p1_prf_pequena",
            "nome": "Polícia Rodoviária Federal — PRF",
            "estado": "Federal",
            "tipo": "Suspensão",
            "edital_url": "https://pesquisa-auto.prf.gov.br/#/pesquisa-edital/consultar-editais",
            "consulta_url": "https://pesquisa-auto.prf.gov.br/#/pesquisa/consultar-debitos",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p1_detran_go_suspensao",
            "nome": "DETRAN GO — Suspensão",
            "estado": "GO",
            "tipo": "Suspensão",
            "edital_url": "https://diariooficial.abc.go.gov.br/buscanova/#/p=1&q=direito%20de%20dirigir",
            "consulta_url": "https://www.go.gov.br/servicos-digitais/detran/consulta-de-processos/meus-processos",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p1_detran_go_placa",
            "nome": "DETRAN GO — Placa",
            "estado": "GO",
            "tipo": "Placa",
            "edital_url": "https://www.go.gov.br/servicos-digitais/detran/consultar-edital-de-notificacao/consultar-edital-de-notificacao",
            "consulta_url": "https://www.go.gov.br/servicos-digitais/detran/consulta-veiculos/lista-veiculos",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p1_detran_ro_autuacao",
            "nome": "DETRAN RO — Processo Adm. Autuação",
            "estado": "RO",
            "tipo": "Autuação",
            "edital_url": "https://www.detran.ro.gov.br/post/categoria/edital-de-notificacao-de-instauracao-de-processo",
            "consulta_url": "https://centralservicos.detran.ro.gov.br/Login?ReturnUrl=%2FProcessoAdministrativo",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p1_detran_ro_penalidade",
            "nome": "DETRAN RO — Processo Adm. Penalidade",
            "estado": "RO",
            "tipo": "Penalidade",
            "edital_url": "https://www.detran.ro.gov.br/post/categoria/edital-de-notificacao-de-penalidade",
            "consulta_url": "https://centralservicos.detran.ro.gov.br/Login?ReturnUrl=%2FProcessoAdministrativo",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p1_detran_ro_cassacao",
            "nome": "DETRAN RO — Cassação",
            "estado": "RO",
            "tipo": "Cassação",
            "edital_url": "https://www.detran.ro.gov.br/post/categoria/editais-de-penalidade-de-cassacao-de-cnh",
            "consulta_url": "https://centralservicos.detran.ro.gov.br/Login?ReturnUrl=%2FProcessoAdministrativo",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p1_detran_ro_notif_autuacao",
            "nome": "DETRAN RO — Notificação de Autuação (Multa)",
            "estado": "RO",
            "tipo": "Multa",
            "edital_url": "https://www.detran.ro.gov.br/post/categoria/notificacao-de-autuacao",
            "consulta_url": "",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p1_detran_ro_notif_penalidade",
            "nome": "DETRAN RO — Notificação de Penalidade (Multa)",
            "estado": "RO",
            "tipo": "Multa",
            "edital_url": "https://www.detran.ro.gov.br/post/categoria/editais-de-notificacao-de-penalidade-multa",
            "consulta_url": "",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p1_detran_ms_diario",
            "nome": "DETRAN MS — Diário de Notificação",
            "estado": "MS",
            "tipo": "Notificação",
            "edital_url": "https://www.diariooficial.ms.gov.br",
            "consulta_url": "https://www2.detran.ms.gov.br/pdf-completo/pdfcompleto.html",
            "consulta_url2": "https://www2.meudetran.ms.gov.br/infracao.php",
            "tutorial_url": "",
        },
    ],

    "Prioridade 2": [
        {
            "id": "p2_der_mg_multas",
            "nome": "DER MG — Multas",
            "estado": "MG",
            "tipo": "Multa",
            "edital_url": "https://www.der.mg.gov.br/multas/editais-de-autuacao-penalidade-apos-15-de-junho-de-2021",
            "consulta_url": "https://portal.der.mg.gov.br/portal-servicos-frontend/dynamic-menu-public/6",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p2_detran_mg_placa",
            "nome": "DETRAN MG — Autuação e Penalidade (Placa)",
            "estado": "MG",
            "tipo": "Placa",
            "edital_url": "https://detran.mg.gov.br/infracoes/multa/consulta-de-edital-de-autuacao-multa-e-advertencia",
            "consulta_url": "https://detran.mg.gov.br/veiculos/situacao-do-veiculo/consultar-situacao-do-veiculo",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p2_detran_es_processo",
            "nome": "DETRAN ES — Processo Administrativo",
            "estado": "ES",
            "tipo": "Suspensão",
            "edital_url": "https://detran.es.gov.br/GrupodeArquivos/editais-de-notificacao-de-suspensao",
            "consulta_url": "https://processoeletronico.es.gov.br/?protocolo=",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p2_detran_es_placa",
            "nome": "DETRAN ES — Placa",
            "estado": "ES",
            "tipo": "Placa",
            "edital_url": "https://detran.es.gov.br/editais-de-notificacao-de-multa",
            "consulta_url": "https://publicodetran.es.gov.br/AutosDigitalizados/ConsultaAutoDigitalizado.aspx",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p2_detran_se",
            "nome": "DETRAN SE",
            "estado": "SE",
            "tipo": "Suspensão",
            "edital_url": "https://www.detran.se.gov.br/portal/?pg=consulta_edital_notificacao",
            "consulta_url": "https://www.detran.se.gov.br/portal/?pg=cnh_consulta_dados",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p2_der_df_autuacao",
            "nome": "DER DF — Autuação",
            "estado": "DF",
            "tipo": "Autuação",
            "edital_url": "https://www.der.df.gov.br/notificacao-de-autuacao",
            "consulta_url": "https://radar.serpro.gov.br/main.html#/cidadao",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p2_der_df_penalidade",
            "nome": "DER DF — Penalidade",
            "estado": "DF",
            "tipo": "Penalidade",
            "edital_url": "https://arquivos.der.df.gov.br/NOT?tipo=2",
            "consulta_url": "https://radar.serpro.gov.br/main.html#/cidadao",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p2_detran_mt",
            "nome": "DETRAN MT",
            "estado": "MT",
            "tipo": "Suspensão",
            "edital_url": "https://www.iomat.mt.gov.br/buscanova/#/p=1&q=Suspensão%20do%20Direito%20de%20Dirigir",
            "consulta_url": "https://www.detran.mt.gov.br/consulte-sua-habilitacao",
            "consulta_url2": "",
            "tutorial_url": "",
        },
    ],

    "Prioridade 3": [
        {
            "id": "p3_detran_rs",
            "nome": "DETRAN RS — Adm. e Placa",
            "estado": "RS",
            "tipo": "Suspensão",
            "edital_url": "https://www.detran.rs.gov.br/",
            "consulta_url": "https://pcsdetran.rs.gov.br/login?redirectUrl=%2Fprocessos-penalidades%3Flista%3Dterceiros",
            "consulta_url2": "https://pcsdetran.rs.gov.br/login?redirectUrl=%2Fconsulta-infracoes",
            "tutorial_url": "",
        },
        {
            "id": "p3_detran_df",
            "nome": "DETRAN DF — Processo Administrativo",
            "estado": "DF",
            "tipo": "Suspensão",
            "edital_url": "https://dodf.df.gov.br/dodf/materia/busca?termo=%22DIREITO%20DE%20DIRIGIR%22&data=2026-03-26",
            "consulta_url": "",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p3_prf_grande",
            "nome": "PRF — Notificação Edital (Grande)",
            "estado": "Federal",
            "tipo": "Notificação",
            "edital_url": "https://www.gov.br/prf/pt-br/assuntos/notificacao-por-edital/notificacao-edital-na",
            "consulta_url": "https://cpag.prf.gov.br/multas",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p3_rioverde_autuacao",
            "nome": "Prefeitura Rio Verde — Autuação",
            "estado": "GO",
            "tipo": "Autuação",
            "edital_url": "https://www.rioverde.go.gov.br/amt/download/edital-de-notificacao-de-instauracao-do-processo-administrativo-de-suspensao-do-direito-de-dirigir/",
            "consulta_url": "https://www.go.gov.br/servicos-digitais/detran/consulta-de-processos/meus-processos",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p3_rioverde_penalidade",
            "nome": "Prefeitura Rio Verde — Penalidade",
            "estado": "GO",
            "tipo": "Penalidade",
            "edital_url": "https://www.rioverde.go.gov.br/amt/download/edital-de-notificacao-de-aplicacao-da-penalidade-de-suspensao-do-direito-de-dirigir/",
            "consulta_url": "https://www.go.gov.br/servicos-digitais/detran/consulta-de-processos/meus-processos",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p3_der_goias",
            "nome": "DER Goiás",
            "estado": "GO",
            "tipo": "Multa",
            "edital_url": "https://www.goinfra.go.gov.br/multas",
            "consulta_url": "",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p3_dnit",
            "nome": "DNIT",
            "estado": "Federal",
            "tipo": "Multa",
            "edital_url": "https://servicos.dnit.gov.br/multas/informacoes/editais-publicacao-notificacao?ano=2026",
            "consulta_url": "https://servicos.dnit.gov.br/multas/consulta-multas/veiculo",
            "consulta_url2": "",
            "tutorial_url": "",
        },
    ],

    "Prioridade 4": [
        {
            "id": "p4_detran_pr",
            "nome": "DETRAN PR",
            "estado": "PR",
            "tipo": "Suspensão",
            "edital_url": "https://www.detran.pr.gov.br/webservices/der/notificacoes",
            "consulta_url": "https://www.detran.pr.gov.br/servicos/consultar-recurso-de-pontuacao-suspensao-cnh",
            "consulta_url2": "https://www.geproc.pr.gov.br/geproc/ng/pub/processo/multas;route=pub%2Fprocesso%2Fmultas;_publico=true",
            "tutorial_url": "",
        },
        {
            "id": "p4_der_pr",
            "nome": "DER PR",
            "estado": "PR",
            "tipo": "Multa",
            "edital_url": "https://www.der.pr.gov.br/webservices/der/notificacoes",
            "consulta_url": "https://www.geproc.pr.gov.br/geproc/ng/pub/processo/multas;route=pub%2Fprocesso%2Fmultas;_publico=true",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p4_detran_ba",
            "nome": "DETRAN BA",
            "estado": "BA",
            "tipo": "Multa",
            "edital_url": "https://transonline.salvador.ba.gov.br/conteudo/index.php/multa/publicacoes",
            "consulta_url": "https://transonline.salvador.ba.gov.br/conteudo/index.php/multa/consultaProcessoMulta",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p4_detran_sc",
            "nome": "DETRAN SC",
            "estado": "SC",
            "tipo": "Suspensão",
            "edital_url": "https://portal.doe.sea.sc.gov.br/v2.42.00/#/portal/edicao/buscar-publicacao",
            "consulta_url": "https://servicos.detran.sc.gov.br/consulta-dossie-veiculo",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p4_der_es",
            "nome": "DER ES",
            "estado": "ES",
            "tipo": "Notificação",
            "edital_url": "https://der.es.gov.br/notificacoes-de-transito-2026",
            "consulta_url": "",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p4_der_rj",
            "nome": "DER RJ",
            "estado": "RJ",
            "tipo": "Notificação",
            "edital_url": "https://sgitp.der.rj.gov.br/editais",
            "consulta_url": "",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p4_detran_pa",
            "nome": "DETRAN PA",
            "estado": "PA",
            "tipo": "Suspensão",
            "edital_url": "https://www.detran.pa.gov.br/sistransito/detran-web/servicos/veiculos/indexEdital.jsf",
            "consulta_url": "https://sistemas-renavam.detran.pa.gov.br/sistransito/detran-web/servicos/infracao/indexConsultaInfracao.jsf",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p4_detran_ac",
            "nome": "DETRAN AC",
            "estado": "AC",
            "tipo": "Suspensão",
            "edital_url": "https://diario.ac.gov.br",
            "consulta_url": "https://www.detran.ac.gov.br/portal-de-servicos-detran-ac/",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p4_detran_ap",
            "nome": "DETRAN AP",
            "estado": "AP",
            "tipo": "Suspensão",
            "edital_url": "https://diofe.portal.ap.gov.br/buscanova/#/p=1&q=%22direito%20de%20dirigir%22",
            "consulta_url": "",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p4_detran_pe",
            "nome": "DETRAN PE",
            "estado": "PE",
            "tipo": "Autuação",
            "edital_url": "https://www.detran.pe.gov.br/como-fazer/infracoes/editais-de-autuacao",
            "consulta_url": "https://online8.detran.pe.gov.br/DetranPessoal/PortalServicos/LoginGov?servico_uri=https://online7.detran.pe.gov.br/MvcHabilitacao/Consultar/ConsultaHabilitacao",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p4_detran_rn",
            "nome": "DETRAN RN",
            "estado": "RN",
            "tipo": "Notificação",
            "edital_url": "https://portal.detran.rn.gov.br/servicos/publicacoes/editaisnotificacoes",
            "consulta_url": "https://portal.detran.rn.gov.br/servicos/processos/consultaprocesso",
            "consulta_url2": "",
            "tutorial_url": "",
        },
        {
            "id": "p4_detran_to",
            "nome": "DETRAN TO",
            "estado": "TO",
            "tipo": "Suspensão",
            "edital_url": "https://internet.detran.to.gov.br/notificacao/notificacoes.asp",
            "consulta_url": "https://www.to.gov.br/detran/cnh",
            "consulta_url2": "",
            "tutorial_url": "",
        },
    ],
}

PRIORITY_COLORS = {
    "Prioridade 1": "#e94560",
    "Prioridade 2": "#f5a623",
    "Prioridade 3": "#4a9eff",
    "Prioridade 4": "#8b949e",
}

PRIORITY_LABELS = {
    "Prioridade 1": "🔴 PRIORIDADE 1",
    "Prioridade 2": "🟡 PRIORIDADE 2",
    "Prioridade 3": "🔵 PRIORIDADE 3",
    "Prioridade 4": "⚪ PRIORIDADE 4",
}
